export const ErrorCodes = {
  NO_INTERNET: 'NO_INTERNET',
  SERVER_UNAVAILABLE: 'SERVER_UNAVAILABLE',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  MATCH_STARTED: 'MATCH_STARTED',
  MATCH_CANCELLED: 'MATCH_CANCELLED',
  SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_VERIFICATION_PENDING: 'PAYMENT_VERIFICATION_PENDING',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  DUPLICATE_JOINING: 'DUPLICATE_JOINING',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUND_FAILED: 'REFUND_FAILED',
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
  APP_UPDATE_REQUIRED: 'APP_UPDATE_REQUIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  ROOM_CREDENTIALS_LOCKED: 'ROOM_CREDENTIALS_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: unknown;
}
